[package]
name = "mavlink-debugger"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.45", features = ["derive"] }
crossterm = "0.29.0"
mavlink = "0.15.0"
ratatui = "0.29.0"
color-eyre="0.6.5"
